version: "3"

services:
  finance-manager:
    build:
      context: ./src
      dockerfile: "Dockerfile"
    image: finance-manager:latest
    ports:
      - "8080:80"
    environment:
      FinanceApiUrl: "http://localhost:5001"
